FROM node:18-alpine

WORKDIR /app

COPY package*.json ./
RUN npm install

COPY prisma ./prisma/

RUN npx prisma generate --schema=prisma/schema/schema.prisma

COPY tsconfig.json ./
COPY src ./src

EXPOSE 3000
CMD ["sh", "-c", "npx prisma migrate deploy && npm run dev"]
